#------------------------------------------------------------------------------------
# Workflow configuration
#------------------------------------------------------------------------------------
name: Deployments

on:
  push:
    branches:
      - main

#------------------------------------------------------------------------------------
# Define application permissions & version
#------------------------------------------------------------------------------------
permissions: write-all

#------------------------------------------------------------------------------------
# Workflow jobs (Linux only)
#------------------------------------------------------------------------------------
jobs:

  #----------------------------------------------------------------------------------
  # build server and apps
  #----------------------------------------------------------------------------------
  build-client:
    name: Build and test client app
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app/client
    steps:
      - uses: actions/checkout@v3
      #------------------------------------------------------------------------------
      # install
      #------------------------------------------------------------------------------
      - name: Install dependencies
        run: |
          npm install

      #------------------------------------------------------------------------------
      # build
      #------------------------------------------------------------------------------
      - name: Build packages
        run:  npm run build
