#------------------------------------------------------------------------------------
# Workflow configuration
#------------------------------------------------------------------------------------
name: Integrations

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]
    paths-ignore: [doc/**]

#------------------------------------------------------------------------------------
# Define application permissions & version
#------------------------------------------------------------------------------------
permissions: read-all

#------------------------------------------------------------------------------------
# Workflow jobs (Linux only)
#------------------------------------------------------------------------------------
jobs:
  #----------------------------------------------------------------------------------
  # check the title of pull request
  #----------------------------------------------------------------------------------
  validate-pull-request:
    runs-on: ubuntu-latest
    name: Verify pull request
    steps:
      - name: Verify pull request title match standard
        uses: deepakputhraya/action-pr-title@master
        with:
          regex: '(chore|feat|fix)+: ([a-z])+'
          allowed_prefixes: 'feat,fix,chore'
          disallowed_prefixes: 'feat/,hotfix'
          prefix_case_sensitive: false
          min_length: 10
          max_length: 120
          github_token: ${{ github.token }}

  #----------------------------------------------------------------------------------
  # build packages and apps
  #----------------------------------------------------------------------------------
  build-client:
    name: Build and test client app
    needs: validate-pull-request
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/client
    steps:
      - uses: actions/checkout@v3
      #------------------------------------------------------------------------------
      # install
      #------------------------------------------------------------------------------
      - name: Install dependencies
        run: |
          npm install

      #------------------------------------------------------------------------------
      # build
      #------------------------------------------------------------------------------
      - name: Build packages
        run:  npm run build
