#------------------------------------------------------------------------------------
# Workflow configuration
#------------------------------------------------------------------------------------
name: Integrations

on:
    pull_request:
        types: [opened, edited, synchronize, reopened, ready_for_review]
        paths-ignore: [doc/**]

#------------------------------------------------------------------------------------
# Define application permissions & version
#------------------------------------------------------------------------------------
permissions: read-all

#------------------------------------------------------------------------------------
# Workflow jobs (Linux only)
#------------------------------------------------------------------------------------
jobs:
    #----------------------------------------------------------------------------------
    # build server and apps
    #----------------------------------------------------------------------------------
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up python
              id: setup-python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'

            #------------------------------------------------------------------------------
            # install
            #------------------------------------------------------------------------------
            - name: Install Poetry
              uses: snok/install-poetry@v1
              with:
                virtualenvs-create: true
                virtualenvs-in-project: true
                installer-parallel: true

            - name: Install dependencies
              run: |
                make install

            #------------------------------------------------------------------------------
            # build
            #------------------------------------------------------------------------------
            - name: Build packages
              run:  make build
